### ISSUE TITLE
一部の図の説明はあっていますか?

### ISSUE THREAD

**Issue by ishiayaya** [JPBAP-SQLBI/blog#52]
> 読み込み順序については、実際に弊社サポートで検証した結果、次のような挙動になることを確認しています。
の後の
> 先に大文字が含まれる文字列が保存される場合
と
> 先に小文字が含まれる文字列が保存される場合
は説明と図が逆ではないでしょうか?

---

#### Document Details

⚠ *Do not edit this section.

* ID: fae55e0d-9954-53d3-a1c9-2b68a229dd89
* 対象記事: [Power BI での大文字小文字の区別](https://jpbap-sqlbi.github.io/blog/powerbi/pbi_model_character_tips/)
* Content Source: [articles/powerbi/pbi_model_character_tips.md](https://github.com/jpbap-sqlbi/blog/blob/main/articles/powerbi/pbi_model_character_tips.md)
* Author:

**Comment by Hyamyam** [comment]
@ishiayaya さん、ご指摘いただきありがとうございます。
仰る通り説明と図が相違していましたので、修正いたしました。

![image](https://user-images.githubusercontent.com/73410575/163109249-606b191f-1d66-4af4-a58d-ea24d0466386.png)

当 Issue はこちらにて Close させていただきます。
