### ISSUE TITLE
誤記あります

### ISSUE THREAD

**Issue by ishiayaya** [JPBAP-SQLBI/blog#68]
> Power Bi サービス

Power BI サービス

---

#### Document Details

⚠ *Do not edit this section.

* ID: 662ecb7c-d4d2-50a8-a219-1dc6f776c7e2
* 対象記事: [Power BI ライセンスに関するよくある質問(FAQ)](https://jpbap-sqlbi.github.io/blog/powerbi/pbi_license_faq/)
* Content Source: [articles/powerbi/pbi_license_faq.md](https://github.com/jpbap-sqlbi/blog/blob/main/articles/powerbi/pbi_license_faq.md)
* Author:

**Comment by Hyamyam** [comment]
@ishiayaya さん、いつもありがとうございます。

修正いたしました。
![image](https://user-images.githubusercontent.com/73410575/188034477-f9c3e789-dfe0-430c-9c31-81d96720f4e3.png)
