### ISSUE TITLE
図の参照が404です

### ISSUE THREAD

**Issue by ishiayaya** [JPBAP-SQLBI/blog#69]
「データマート」についての冒頭の図の参照が

> 404
> File not found

になっています。

---

#### Document Details

⚠ *Do not edit this section.

* ID: 37d164ad-d232-5f7a-8a2b-db64e50db27f
* 対象記事: [Power BI データフローとデータセット及びデータマートの紹介と比較](https://jpbap-sqlbi.github.io/blog/powerbi/pbi_dataflow_dataset/)
* Content Source: [articles/powerbi/pbi_dataflow_dataset.md](https://github.com/jpbap-sqlbi/blog/blob/main/articles/powerbi/pbi_dataflow_dataset.md)
* Author:

**Comment by Hyamyam** [comment]
@ishiayaya さん、いつもありがとうございます。

冒頭の図、こちらのことかと思いますが、どのように見ると 404 となりますでしょうか。
![image](https://user-images.githubusercontent.com/73410575/188034624-9b43b660-c12e-4fe0-b88b-8c2e2314df27.png)

以下画像ファイル自体もアクセス可能ですか？
https://jpbap-sqlbi.github.io/blog/powerbi/pbi_dataflow_dataset/dataflow.png

**Comment by ishiayaya** [comment]
@Hyamyam データマートの下の図です。

**Comment by ishiayaya** [comment]
@Hyamyam https://jpbap-sqlbi.github.io/blog/powerbi/pbi_dataflow_dataset/datamart.png

**Comment by Hyamyam** [comment]
ありがとうございます。
修正いたしました。

![image](https://user-images.githubusercontent.com/73410575/188040556-aaa7bfbc-cb29-4c79-aafb-ab49de97caa8.png)
